
version: '3.9'

services:
  roschools-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roschools-hub
    ports:
      - "8414:8414"
    restart: unless-stopped
    networks:
      - roschools-network

networks:
  roschools-network:
    driver: bridge
